name: ci
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  linux-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Build Swift Package on Linux"
        run: swift build
      - name: "Cross-compile Swift Package to Android"
        uses: skiptools/swift-android-action@v2
        with:
          run-tests: false
  macos-android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Build Swift Package on macOS"
        run: swift build
      - name: "Cross-compile Swift Package to Android"
        uses: skiptools/swift-android-action@v2
        with:
          run-tests: false

